version: '3'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '$DB_ROOT_PASSWORD'
      MYSQL_DATABASE: '$DB_NAME'
      MYSQL_USER: '$DB_USER'
      MYSQL_PASSWORD: '$DB_PASSWORD'
    ports:
      - '$DB_PORT:3306'
